### ISSUE TITLE
Migrate to Node.js native test runner

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/utils#18]
Remove esm-tape-runner and tap-monkey to use the Node.js native runner.

https://nodejs.org/api/test.html

[i18n](https://github.com/NodeSecure/i18n) has been migrated few days ago (so do not hesitate to check the scripts and tests).

**Comment by MaximeMRF** [comment]
Hello, I take this issue.

**Comment by fraxken** [comment]
Thanks for the contribution!
